### ISSUE TITLE
Free text support question

### ISSUE THREAD

**Issue by doug-newman-nasa** [stac-api-extensions/collection-search#13]
Are you suggesting that 'free text' filtering be a separate extension or are you going to define it here? If not here then does such an extension exist?

**Comment by m-mohr** [comment]
The Free-Text Search extension is defined here: https://github.com/cedadev/stac-freetext-search

The Collection Search extension simply re-uses it. (I guess we should link back from here to there...)

**Comment by doug-newman-nasa** [comment]
Excellent. Thanks.
