### ISSUE TITLE
rel="queryables" and filter extension in context of collection-search

### ISSUE THREAD

**Issue by ycespb** [stac-api-extensions/collection-search#3]
The proposed collection-search extension descriptions refers to the "Filter Extension", it is not clear however where the queryables available for constructing the collection search request (with a filter) can be discovered.  Should it be stated that in case the "collection-search" extension is combined with "filter", that the /queryables endpoint (and rel="queryables") publishes the queryables available for collection-search (while normally these are queryables for item-search) or could/should an additional relation be defined rel="collection-queryables" ?

**Comment by m-mohr** [comment]
Does OGC say anything about it in Records? That's our baseline and, if they don't take care of it, we should probably forward this issue to them.

The queryables rel type could be returned by /collections though so there's no conflict IMHO.

**Comment by ycespb** [comment]
@m-mohr , I have opened an issue in the API-Records Github at https://github.com/opengeospatial/ogcapi-records/issues/196 for this issue.  In the meanwhile, we will already put the queryables rel type as you suggest in the /collections response.  Should that not already be put in the collection-search extension awaiting a final solution/guidance by API-Records ?

**Comment by m-mohr** [comment]
There are some things we still need to clarify, it seems: https://github.com/opengeospatial/ogcapi-features/issues/830

**Comment by m-mohr** [comment]
Should be clarified in https://github.com/stac-api-extensions/collection-search/commit/bf79a94688d3bd4e177390a198cd155f77253128
