### ISSUE TITLE
Adding simple text search to list of default query parameters

### ISSUE THREAD

**Issue by chiarch84** [stac-api-extensions/collection-search#6]
I think that in this [list of default query parameters](https://github.com/stac-api-extensions/collection-search#basics) a simple text search should be added.

I believe that collections search is mostly done by text search and then in second and third instances by bbox and time. I might be wrong, but I for sure think that text search is one of the most used searches in this case.

**Comment by m-mohr** [comment]
Free-text search is an independent specification, I think: https://github.com/cedadev/stac-freetext-search

**Comment by chiarch84** [comment]
Thanks I didn't know about it. Even though this seems more for items search rather than for collections search.

**Comment by m-mohr** [comment]
True, we'd need to extend this for collection search, but the functionality is the same, just a different endpoint that accepts the q parameter either in text for json. Maybe open an issue in the extension repo? Happy to link to it from here, but not so happy to copy all the specification from there into here ;-)

**Comment by chiarch84** [comment]
sure maybe better to open an issue there! I'll do it!

**Comment by m-mohr** [comment]
Actually, we inherit q and some other parameters directly from OGC API - Records: https://docs.ogc.org/DRAFTS/20-004.html#_parameter_q

We need to ensure we document all that properly here.

**Comment by m-mohr** [comment]
Added a proposal.
